title: Mario Leone — AI Engineer
description: C++/Python • Trading Systems • ML/LLM
url: "https://portfolio.leoneconsulting.dev"
baseurl: ""

remote_theme: alshedivat/al-folio
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

# Navbar links
navbar-links:
  Home: "/"
  Projects: "/projects/"
  CV: "/assets/cv.pdf"
  Contact: "/#contact"

# Footer links
footer-links:
  github: "https://github.com/AstroMarius"
  linkedin: "https://linkedin.com/in/mario-leone-dev"

# Appearance
darkmode: true

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
