title: "Mario Leone"
description: "C++/Python • Trading Systems • ML/LLM"
url: "https://portfolio.leoneconsulting.dev"
baseurl: ""

# Theme
remote_theme: "AstroMarius/al-folio"

# plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-scholar

# Navbar links (array of single-key maps; preferred for Liquid iterations)
navbar-links:
  - Home: "/"
  - Projects: "/projects/"
  - CV: "/assets/cv.pdf"
  - Contact: "/#contact"

# Footer links
footer-links:
  github: "https://github.com/AstroMarius"
  linkedin: "https://linkedin.com/in/mario-leone-dev"

# Appearance
darkmode: true

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
