title: "Mario Leone"
description: "C++/Python • Trading Systems • ML/LLM"
url: "https://portfolio.leoneconsulting.dev"
baseurl: ""

# Logo
logo: "/assets/img/logo.png"

# Theme
# Vendorizzato theme al-folio; remote_theme removed

# Layout
navbar_fixed: true
footer_fixed: true

# plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Navbar links (array of single-key maps; preferred for Liquid iterations)
navbar-links:
  # Use sequence of [label, path] pairs for simpler iteration
  - ["Home", "/"]
  - ["Projects", "/projects/"]
  - ["CV", "/cv/"]
  - ["Contact", "/#contact"]

# Footer links
footer-links:
  github: "https://github.com/AstroMarius"
  linkedin: "https://linkedin.com/in/mario-leone-dev"

# Appearance
darkmode: true


